# Generated by Django 3.2.7 on 2021-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210921_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='rank_badge',
            field=models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Master')], default=0, max_length=2),
        ),
    ]
