# Generated by Django 3.2.7 on 2021-09-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_buyer_rank_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='rank_badge',
            field=models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Master')], default=0),
        ),
    ]
