# Generated by Django 3.2.7 on 2021-09-26 20:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.default_profile_image, max_length=255, null=True, upload_to=''),
        ),
    ]
