# Generated by Django 3.2.7 on 2021-09-27 09:52

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='rank_badge',
        ),
        migrations.AddField(
            model_name='buyer',
            name='reviews',
            field=models.FloatField(default=5, verbose_name='Review'),
        ),
        migrations.AddField(
            model_name='seller',
            name='reviews',
            field=models.FloatField(default=5, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.default_profile_image, max_length=255, null=True, upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
