# Generated by Django 3.2.7 on 2021-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210927_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rank_badge',
            field=models.IntegerField(choices=[('0', 'Bronze'), ('1', 'Silver'), ('2', 'Gold'), ('3', 'Master')], default=0),
        ),
    ]
