# Generated by Django 3.2.7 on 2021-10-11 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20211012_0334'),
        ('accounts', '0018_alter_seller_rank_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-rating']},
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='reviews',
        ),
        migrations.AddField(
            model_name='seller',
            name='clicks',
            field=models.PositiveBigIntegerField(default=0, verbose_name='profile visits'),
        ),
        migrations.AddField(
            model_name='seller',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='games.SellerGame'),
        ),
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.FloatField(default=5, verbose_name='Rating'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=5, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Review Comment')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.seller')),
            ],
        ),
    ]
