# Generated by Django 3.2.7 on 2021-10-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211012_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='reviews',
            field=models.FloatField(default=5, verbose_name='Rating'),
        ),
    ]
