# Generated by Django 3.2.7 on 2021-10-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_buyer_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
