# Generated by Django 3.2.7 on 2021-10-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='games',
        ),
    ]
