# Generated by Django 3.2.7 on 2021-10-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211012_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
