# Generated by Django 3.2.7 on 2021-10-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='time_limit_in_hours_for_changing_requirements',
            field=models.PositiveBigIntegerField(default=8),
        ),
    ]
