# Generated by Django 3.2.7 on 2021-11-14 20:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='providing_services_to_number_of_games',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of Games'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar.png', max_length=255, upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
