# Generated by Django 3.2.7 on 2021-09-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210925_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(related_name='category', to='games.Category'),
        ),
    ]
