# Generated by Django 3.2.7 on 2021-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dummy',
            field=models.CharField(default='3', max_length=5),
        ),
    ]
