# Generated by Django 3.2.7 on 2021-10-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='categories',
        ),
    ]
