# Generated by Django 3.2.7 on 2021-10-11 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_category_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dummy',
        ),
        migrations.CreateModel(
            name='SellerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('seller_description_of_game', models.TextField(blank=True, null=True, verbose_name='Description of Game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_game', to='games.game')),
            ],
        ),
    ]
