# Generated by Django 3.2.7 on 2021-10-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20211012_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dummy',
            field=models.CharField(default='3', max_length=5),
        ),
    ]
