# Generated by Django 3.2.7 on 2021-10-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dummy',
        ),
    ]
