# Generated by Django 3.2.7 on 2021-10-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211012_1201'),
        ('games', '0010_remove_game_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellergame',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='accounts.seller'),
        ),
    ]
