# Generated by Django 3.2.7 on 2021-10-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_sellergame_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerGame',
        ),
    ]
