# Generated by Django 3.2.7 on 2021-10-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211012_1201'),
        ('games', '0012_delete_sellergame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('seller_description_of_game', models.TextField(blank=True, null=True, verbose_name='Description of Game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_game', to='games.game')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='accounts.seller')),
            ],
        ),
    ]
