# Generated by Django 3.2.7 on 2021-10-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_review'),
        ('games', '0014_auto_20211012_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='sellergame',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_games', to='accounts.seller'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=5, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Review Comment')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.seller')),
            ],
        ),
    ]
