# Generated by Django 3.2.7 on 2021-10-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_review'),
        ('games', '0015_auto_20211018_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.buyer'),
            preserve_default=False,
        ),
    ]
