# Generated by Django 3.2.7 on 2021-10-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_review_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
