# Generated by Django 3.2.7 on 2021-09-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_game_dummy'),
        ('accounts', '0018_alter_seller_rank_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaming_account_id', models.CharField(max_length=100, verbose_name='Your Gaming Accound ID')),
                ('gaming_account_password', models.CharField(max_length=50, verbose_name='Password')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=999)),
                ('order_start_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_days_for_completing_the_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('at', 'Active'), ('cp', 'Completed'), ('dl', 'Delivered'), ('cd', 'Canceled')], max_length=2)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.buyer')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Select Game')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.seller')),
            ],
        ),
    ]
