# Generated by Django 3.2.7 on 2021-10-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_category_game_categories'),
        ('orders', '0003_alter_order_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='games.game', verbose_name='Select Game'),
        ),
    ]
