# Generated by Django 3.2.7 on 2021-10-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211023_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
