# Generated by Django 3.2.7 on 2021-10-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.RemoveField(
            model_name='review',
            name='seller',
        ),
    ]
